---
- hosts: localhost
  gather_facts: no
  module_defaults:
     group/aws:
       region: "us-east-1"
  tasks:
     - name: create target group
       elb_target_group:
          name: M5igtg
          protocol: tcp
          port: 80
          stickiness_enabled: no
          stickiness_type: source_ip
          vpc_id: "{{ vpc.vpc.id }}"
          unhealthy_threshold_count: 3
          healthy_threshold_count: 3
          health_check_interval: 30
          state: present
       register: M5_ig_tg
     - name: launch template
       ec2_launch_template:
          name: M5-ig-lt
          image_id: "ami-09d95fab7fff3776c"
          key_name: auburndemo1
          instance_type: t3.micro
          security_groups: "{{ M5_endpoint_tag.group_id }},{{ nginx_servers.group_id }},{{ M5_ig_postgres_tag.group_id }}"
          tags:
             Name: M5-ig-asg-server
          iam_instance_profile: image-gallery-server-role
       register: ig_lt
     - name: allocate a new elastic IP without associating it to anything
       ec2_eip:
          state: present
       register: eip1
     - name: allocate a new elastic IP without associating it to anything
       ec2_eip:
          state: present
       register: eip2
     - name: create network load balancer
       elb_network_lb:
          name: M5-ig-nlb
          subnet_mappings:
             - SubnetId: "{{ M5_ig_private_1.subnet.id }}"
               AllocationId: "{{ eip1.allocation_id }}"
             - SubnetId: "{{ M5_ig_private_2.subnet.id }}"
               AllocationId: "{{ eip2.allocation_id }}"
          listeners:
             - Protocol: TCP
               Port: 80
               DefaultActions:
                  - Type: forward
                    TargetGroupName: "{{ M5_ig_tg.target_group_name }}"
             - Protocol: TLS
               Port: 443
               Certificates:
                  - CertificatesArn: "c5dcc56b-263d-4e71-a3b4-17356ade1b52"
               DefaultActions:
                  - Type: forward
                    TargetGroupName: "{{ M5_ig_tg.target_group_name }}"
          state: present
