---
- hosts: localhost
  gather_facts: no
  module_defaults:
  tasks:
     - name: add elastic IPs to Route53
       route53:
          state: present
          zone: gingernorrell.com
          record: gingernorrell.com
          type: A
          ttl: 300
          value: 
             - "{{ eip1.allocation_id }}"
             - "{{ eip2.allocation_id }}"
          overwrite: yes
          wait: yes
