---
- hosts: localhost
  gather_facts: no
  module_defaults:
     group/aws:
       region: "us-east-1"
  tasks:
     - name: add secrets manager
       aws_secret:
               name: 'M5-sec-ig'
               state: present
               secret_type: 'string'
               secret: "{{ lookup( 'file', 'secrets.json') }}"
       register: secret

