---
- hosts: localhost
  gather_facts: no
  vars:
     ami_id: "ami-09d95fab7fff3776c"
  module_defaults: 
     group/aws:
        region: "us-east-1"
  tasks: 
     - name: Provision Bobs EC2 instance
       ec2: 
          key_name: auburndemo1
          instance_type: t3.nano
          image: "{{ ami_id }}"
          instance_tags: 
             Name: Module5 Bob
             Module: 5
          wait: yes
          assign_public_ip: yes
          vpc_subnet_id: "{{ M5_ig_public_1.subnet.id }}"
          exact_count: 1
          count_tag:
             Name: Module5 Bob
