---
- hosts: localhost
  gather_facts: no
  module_defaults:
     group/aws:
       region: "us-east-1"
  tasks:
     - name: create target group
       elb_target_group:
          name: M5-ig-tg
          protocol: http
          port: 80
          vpc_id: "{{ vpc.vpc.id }}"
          unhealthy_threshold_count: 3
          healthy_threshold_count: 3
          health_check_interval: 30
          state: present
       register: M5_ig_tg
     - name: launch template
       ec2_launch_template:
          name: M5-ig-lt
          image_id: "ami-09d95fab7fff3776c"
          key_name: auburndemo1
          instance_type: t3.micro
          security_groups: "{{ M5_endpoint_tag.group_id }},{{ nginx_servers.group_id }},{{ M5_ig_postgres_tag.group_id }}"
          tags:
             Name: M5-ig-asg-server
          iam_instance_profile: image-gallery-server-role
       register: ig_lt
     - name: Create network load balancer
       elb_network_lb:
          name: M5-ig-nlb
          subnets: 
             - "{{ M5_ig_private-1.subnet.id }}"
             - "{{ M5_ig_private-2.subnet.id }}"
          listeners: 
             - Protocol: TCP
               Port: 80
             - Protocol: TLS
               Port: 443
               DefaultActions: 
                  - Type: forward
                    TargetGroupName: "{{ M5_ig_tg }}"
          state: present 
     - name: create autoscaling group
       ec2_asg:
          name: M5-ig-asg
          launch_template:
             version: 'Latest'
             launch_template_name: 'ig-lt'
          min_size: 2
          max_size: 4
          desired_capacity: 2
          vpc_zone_identifier: "{{ M5_ig_public_1.subnet.id }},{{ M5_ig_public_2.subnet.id }}"



